language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r fullth-springboot-webservice *
  - mkdir -p deploy
  - mv fullth-springboot-webservice.zip deploy/fullth-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: fullth-springboot-build
    skip_cleanup: true
    acl: private # zip file access as private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: fullth-springboot-build
    key: fullth-springboot-webservice.zip
    bundle_type: zip
    application: fullth-springboot-webservice
    deployment_group: fullth-springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - "xoghksdla@gmail.com"

